"""empty message

Revision ID: 85db065787ab
Revises: 792190d1d130
Create Date: 2022-07-23 20:24:41.987222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85db065787ab'
down_revision = '792190d1d130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'album_img')
    op.drop_column('albums', 'album_runtime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('album_runtime', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('albums', sa.Column('album_img', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
